apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole-exporter.fullname" . }}
  labels:
    {{ include "pihole-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "pihole-exporter.selector-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{ include "pihole-exporter.labels" . | indent 8 }}
      {{ if .Values.service.annotations }}
      annotations:
        {{ toYaml .Values.service.annotations | nindent 8 }}
      {{ end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.extraEnvVars }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "pihole-exporter.fullname" . }}
          ports:
          - name: httpexporter
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
