apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole-exporter.fullname" . }}
  labels:
    {{ include "pihole-exporter.labels" . | nindent 4 }}
  {{ if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: exporter-port
  selector:
    {{ include "pihole-exporter.selector-labels" . | nindent 4 }}
